### ISSUE TITLE
Building PyTorch extensions using ROCm and Windows is not supported.

### ISSUE THREAD

**Issue by KillyTheNetTerminal** [patientx/ComfyUI-Zluda#12]
![image](https://github.com/patientx/ComfyUI-Zluda/assets/120438550/18e47580-edd1-4c42-a638-273b62aa2dd9)
Hello.. it's me again haha.. Another curious behavior, is there a way to deal with this error? This is the final part of a CRM workflow that generates 3D models. Firstly it asked me to have nvdiffrast installed so I used (pip install git+https://github.com/NVlabs/nvdiffrast.git
) resulting in this error

I have previously been able to run this part of the workflow with CPU in a directml environment but here I get:
![image](https://github.com/patientx/ComfyUI-Zluda/assets/120438550/7ba12b5b-a5b2-424f-8711-f93a5aa27755)

**Comment by patientx** [comment]
It doesn't work like thay here. Both have to be on cuda.

**Comment by KillyTheNetTerminal** [comment]
![image](https://github.com/patientx/ComfyUI-Zluda/assets/120438550/b239aacd-9165-4669-bf22-5240d844c36c)
one should work with CUDA and the other only with CPU, but each gives their respective errors

**Comment by patientx** [comment]
Sorry, if you can somehow use both of cpu or cuda it would work , otherwise I can't help. There are a few instances with zluda not being optimal regarding cuda apps, cudnn requiring ones for example, flash attention , and a few others. It just doesnt work with zluda and probably not going to in the near future especially for our "older models of gpu's" (compared to 7000 series or pro ones) so don't get your hopes up. Read around, maybe there is a workaround or alternative to whatever you are trying to do here.

**Comment by KillyTheNetTerminal** [comment]
Yes, sadly at the moment it is like that. The only thing I can think of is to have two instances of comfyUI, one for that part of the workflow and the other for the one that needs CUDA and works with Zluda :)
