### ISSUE TITLE
My comfy ui wont generate a normal image and my comfy ui is really slow.

### ISSUE THREAD

**Issue by ukatoshinagi** [patientx/ComfyUI-Zluda#29]
### Your question

It just generates a gray image and it is really slow for me, i have a 7800 xt but it takes 59 seconds to generate a 512x512 image. What should i check or fix?
![Opera Snapshot_2024-10-14_201332_127 0 0 1](https://github.com/user-attachments/assets/0b4eb754-933f-484b-a642-4da836d07418)

**Comment by patientx** [comment]
Post log. At least are you seeing your gpu as device :

***----------------------ZLUDA--------------------------***
  ::  ZLUDA detected, disabling non-supported functions.
  ::  (cuDNN, flash_sdp, mem_efficient_sdp disabled)
***-----------------------------------------------------***
  ::  Device: cuda:0 AMD Radeon RX 7800XT [ZLUDA] : native

like this ?

**Comment by ukatoshinagi** [comment]
yes i think so, it looks like this:
Total VRAM 16368 MB, total RAM 15511 MB
pytorch version: 2.3.0+cu118
Set vram state to: NORMAL_VRAM

***----------------------ZLUDA--------------------------***
  ::  ZLUDA detected, disabling non-supported functions.
  ::  (cuDNN, flash_sdp, mem_efficient_sdp disabled)
***-----------------------------------------------------***
  ::  Device: cuda:0 AMD Radeon RX 7800 XT [ZLUDA] : native

**Comment by patientx** [comment]
First tested the exact model you are using and it generates without a problem , and on a side note use the vae provided here for better quality output with orangemix models. (https://huggingface.co/WarriorMama777/OrangeMixs/tree/main/VAEs)

Try with a different model , and try building your own workflow or loading another workflow you downloaded from the web.

Just did a fresh install and used the same model with my rx 6600, no problems at all. Grey image usually is a sign of bad checkpoint or bad workflow. At first I thought you might have an apu and zluda maybe using that instead of you gpu. BUT the device shown is clearly has identified and using your 7800xt.
