### ISSUE TITLE
Error when install.bat

### ISSUE THREAD

**Issue by JarnoABS** [patientx/ComfyUI-Zluda#46]
### Your question

File "C:\ComfyUI-Zluda\venv\lib\site-packages\torch\__init__.py", line 141, in <module>
    raise err
OSError: [WinError 126] No se puede encontrar el módulo especificado. Error loading "C:\ComfyUI-Zluda\venv\lib\site-packages\torch\lib\caffe2_nvrtc.dll" or one of its dependencies.

I have that error and i cant fix it.
I havent code idea.
Thank you so much!

**Comment by patientx** [comment]
Ensure your AMD GPU drivers are up to date
Ensure you don't have any left over nvidia drivers on your system. (You can use Display Driver Uninstaller to uninstall them)
Ensure that HIP SDK 5.7.1 is installed (and not 6.1.2)
Add these to your Environment Variables (if not already there):
HIP_PATH = C:\Program Files\AMD\ROCm\5.7
HIP_PATH_57 = C:\Program Files\AMD\ROCm\5.7
Add this to your System PATH environment variable:
C:\Program Files\AMD\ROCm\5.7\bin
Ensure you're not using Python install from the Windows Store. Download it from here.
Ensure you've installed optimised ROCm library files from ROCmLibs.

Running from command prompt instead of terminal & powershell is another one people said fixed the stuff.

**Comment by JarnoABS** [comment]
how can i add this PATHs?

**Comment by JarnoABS** [comment]
ok, actually its installed but the same error happends when comfyui try to start

**Comment by marcussacana** [comment]
> HIP SDK 5.7.1

If possible put in readme install instructions, after see that is a SDK I didn't had the trouble to install since I just wanted to run some tools, not develop.
Also, the download link in the page that you provided is dead.

**Comment by patientx** [comment]
> > HIP SDK 5.7.1
> 
> If possible put in readme install instructions, after see that is a SDK I didn't had the trouble to install since I just wanted to run some tools, not develop.

It is required to make zluda work. Not for developing in this case.
